Traceback (most recent call last):
  File "/Users/uec/code/mambaforge/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/uec/code/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/uec/code/mambaforge/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/uec/code/mambaforge/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/uec/code/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/uec/code/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/uec/code/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys,os
sys.path.append(os.path.join(os.environ['ATS_SRC_DIR'],'tools', 'utils'))
sys.path.append(os.path.join(os.environ['ATS_SRC_DIR'],'docs', 'documentation', 'source', 'ats_demos'))

import ats_xdmf
import plot_column_data
import numpy as np
from matplotlib import pyplot as plt
import run_demos
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m[38;5;241m,[39m[38;5;21;01mos[39;00m
[0;32m----> 2[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend(os[38;5;241m.[39mpath[38;5;241m.[39mjoin([43mos[49m[38;5;241;43m.[39;49m[43menviron[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mATS_SRC_DIR[39;49m[38;5;124;43m'[39;49m[43m][49m,[38;5;124m'[39m[38;5;124mtools[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mutils[39m[38;5;124m'[39m))
[1;32m      3[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mATS_SRC_DIR[39m[38;5;124m'[39m],[38;5;124m'[39m[38;5;124mdocs[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdocumentation[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124msource[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mats_demos[39m[38;5;124m'[39m))
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mats_xdmf[39;00m

File [0;32m~/code/mambaforge/lib/python3.10/os.py:680[0m, in [0;36m_Environ.__getitem__[0;34m(self, key)[0m
[1;32m    677[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_data[[38;5;28mself[39m[38;5;241m.[39mencodekey(key)]
[1;32m    678[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[1;32m    679[0m     [38;5;66;03m# raise KeyError with the original key value[39;00m
[0;32m--> 680[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m
[1;32m    681[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mdecodevalue(value)

[0;31mKeyError[0m: 'ATS_SRC_DIR'

